CREATE TABLE traffic_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_name VARCHAR(255) NOT NULL,
    road_type VARCHAR(50),
    region VARCHAR(100),
    day_of_week VARCHAR(20),
    hour INTEGER NOT NULL,
    bus_line_count INTEGER,
    vehicle_volume INTEGER,
    avg_speed NUMERIC(10, 2),
    speed_limit INTEGER,
    traffic_level VARCHAR(20),
    event_nearby BOOLEAN,
    weather VARCHAR(50),
    timestamp TIMESTAMP NOT NULL
);