-- V5__create_routes_table.sql
-- Stores bus route geometries previously loaded from GeoJSON files.
-- Migrating to the database eliminates the dependency on large GeoJSON
-- files at runtime, enabling cloud deployment without file storage.

CREATE TABLE routes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico     VARCHAR(20)  NOT NULL,
    direcao     INTEGER      NOT NULL DEFAULT 0,
    destino     VARCHAR(255),
    consorcio   VARCHAR(50),
    tipo_rota   VARCHAR(50),
    extensao    NUMERIC(12,2),
    shape_id    VARCHAR(50),
    geometry    TEXT         NOT NULL  -- GeoJSON LineString coordinates as JSON string
);

-- Index for the most common query pattern: filter by service ID
CREATE INDEX idx_routes_servico  ON routes (servico);
CREATE INDEX idx_routes_direcao  ON routes (direcao);
CREATE INDEX idx_routes_consorcio ON routes (consorcio);
